# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DISCUZ7红包

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  
  schedule:
    - cron: '*/5 * * * *'
  watch:
    types: [started]
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    env:
      BBS7BASEURL: ${{ secrets.BBS7BASEURL }}
      BBS7USERNAME: ${{ secrets.BBS7USERNAME }}
      BBS7PASSWORD: ${{ secrets.BBS7PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#         run: |
#           git clone https://github.com/DJ-clamp/myStuffs.git ~/myStuffs
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: npm install
        run:
#          cd ~/myStuffs
          npm install
      - name: "运行 【DISCUZ7红包】"
        run: 
#           cd ~/myStuffs
          node Tasks/discuz7.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
